settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app-build
  path: .
  commands:
    install:
      status: true
      method: go build ./cmd/members
    run:
      status: true
      method: ./members
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
