version: '3'
services:
  go:
    build: .
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/go/src:cached
      # exclude volumes
      #- /go/src/api/vendor
      #- /go/src/api/swagger
    tty: true
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./gen/http/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml