version: '3'
services:
  go:
    build: .
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/go/src:cached
      # exclude volumes
      #- /go/src/api/vendor
      #- /go/src/api/swagger
    tty: true