openapi: 3.0.3
info:
  title: Coinspace Members
  description: メンバーズサイト
  version: "1.0"
servers:
- url: http://0.0.0.0:8000/api/v1
paths:
  /add/{a}/{b}:
    get:
      tags:
      - members
      summary: add members
      operationId: members#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 217465865381904383
          format: int64
        example: 3226864031920569862
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 5703713078413232962
          format: int64
        example: 3854952180603418076
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: integer
                example: 2366914043927372495
                format: int64
              example: 3349327047810797608
components: {}
